services:
  api_gateway:
    build: api_gateway
    ports:
      - "8000:8000"
    env_file:
      - api_gateway\.env
    networks:
      - app-network
    depends_on:
      - service_users
      - service_orders

  service_users:
    build: service_users
    env_file:
      - service_users\.env
    networks:
      - app-network

  service_orders:
    build: service_orders
    env_file:
      - service_orders\.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
